### ISSUE TITLE
[Suggestion] Repeat last command hotkey

### ISSUE THREAD

**Issue by supersaiyansubtlety** [devs-immortal/bind-cmd#1]
It'd be handy to be able to repeat the most recently run command via a hotkey.

**Comment by kalucky0** [comment]
That's a pretty cool idea. I'll try to implement that after Easter.

**Comment by kalucky0** [comment]
Done. You can now repeat the last command/message by typing `@` in the config menu. I plan to also make it so that you repeat second last, third last etc. using `@1`, `@2` but that's not implemented yet.

**Comment by supersaiyansubtlety** [comment]
Awesome, thanks!
